name: date_range_picker
description: Date Range Pickers use a dialog window to select a range of date on mobile.
version: 2.0.0
author: anicdh <anic.dh@gmail.com>
homepage: https://github.com/anicdh/date_range_picker

environment:
  sdk: ">2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_date_pickers:
    git:
      url: https://github.com/defint/flutter_date_pickers
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter:
#  assets:
#    - assets/ic_arrow_left.svg
#    - assets/ic_arrow_right.svg